services:
  shinobi-sql:
    image: mysql:5.7
    volumes:
      - ./shinobi/mysql:/var/lib/mysql
      - ./shinobi/ShinobiDocker/mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
  
  shinobi:
    build:
      context: ./shinobi/ShinobiDocker
      args:
        SHINOBI_BRANCH: dev
    volumes:
      - /dev/shm/ShinobiRAM:/dev/shm/streams
      - ./shinobi/shinobi:/home/Shinobi
    ports:
      - "8080:8080"
    environment:
      - HOME=/home/Shinobi
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - SHINOBI_UPDATE=false
    restart: unless-stopped
  
  wyze-bridge:
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:latest
    ports:
        - 1935:1935 # RTMP
        - 8554:8554 # RTSP
        - 8888:8888 # HLS
        - 8889:8889 #WebRTC
        - 8189:8189/udp # WebRTC/ICE
        - 5000:5000 # WEB-UI
    environment:
        - WYZE_EMAIL=${WYZE_EMAIL}
        - WYZE_PASSWORD=${WYZE_PASSWORD}
        - API_ID=${WYZE_API_ID}
        - API_KEY=${WYZE_API_KEY}
        - WB_AUTH=True
    restart: unless-stopped
  
  scrypted:
    container_name: scrypted
    image: ghcr.io/koush/scrypted
    platform: linux/arm64
    volumes:
      - ./scrypted/volume:/server/volume
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer ${SCRYPTED_RANDOM_KEY}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    network_mode: host
    logging:
        driver: "none"
    labels:
        - "com.centurylinklabs.watchtower.scope=scrypted"
    restart: unless-stopped