CREATE DATABASE IF NOT EXISTS `Shinobi`;
CREATE USER IF NOT EXISTS 'shinobi'@'%' IDENTIFIED WITH mysql_native_password BY '';
GRANT ALL PRIVILEGES ON Shinobi.* TO 'shinobi'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
